obj=open("abc.txt","w")
obj.write("welcome to sushma marriage function i invite u all to my marriage so please dont miss")
obj.close()
f1=open("abc.txt","r")
print(f1.read(10))
f1.seek(10)
print(f1.read(26))
f1.seek(36)
print(f1.read(29))
f1.seek(65)
print(f1.read(40))
f1.seek(13)
f1.close()